<script lang="ts">
    import { onMount } from "svelte";
    import BillBoard from "@/components/BillBoard.svelte";
    import { showLoading } from "@/global/loading";

    onMount(()=>{
        showLoading.set(false);
    })
</script>
    <BillBoard/>
<div>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et congue ex, et sagittis orci. Integer mollis urna id lacus commodo porta. Aenean et nunc arcu. Sed bibendum leo eu dui mattis volutpat eget at risus. Nunc dapibus justo non finibus porttitor. Sed in aliquet quam, vel interdum elit. Fusce mi leo, blandit et sollicitudin eu, gravida quis lorem. Proin dignissim neque enim, id condimentum diam tincidunt vitae. Aliquam lorem leo, congue a turpis ac, tincidunt gravida libero. Ut et laoreet lorem, vitae porta justo. Fusce vehicula, est sed rutrum bibendum, leo arcu scelerisque orci, eget fringilla ex nisi vitae quam. Donec pharetra, lacus nec tristique finibus, erat velit molestie est, ac iaculis nisl lectus eu massa.

Vestibulum porttitor risus et nisi tempor, et tristique justo hendrerit. Morbi porttitor dui vel tempus imperdiet. Ut lorem mi, suscipit sed sem in, pellentesque vehicula odio. Donec porta mi ut lacus maximus, nec mollis quam tincidunt. Fusce at laoreet odio, a molestie turpis. Sed non est lectus. Praesent eleifend mollis mi, eu pharetra metus tempus vitae. Phasellus at sollicitudin massa. Vestibulum viverra fermentum sem, eget tempus elit fringilla quis. Nunc est diam, accumsan eget vulputate sed, ultricies non magna. Donec sodales dignissim est, et ultrices mauris euismod luctus. Nunc egestas elementum felis vel gravida. Nunc interdum, enim sit amet molestie tempus, elit tellus rutrum justo, nec aliquet urna libero sit amet est. Praesent luctus est massa, quis convallis arcu auctor a. Morbi fermentum velit vel elementum tempus. Donec eu sem nisl.

Morbi aliquam pretium elit, eget placerat leo consequat a. Praesent ut gravida neque, vel mattis ligula. Proin facilisis, turpis vitae blandit vehicula, mauris ex cursus diam, non viverra est nisi eu turpis. Mauris in maximus arcu, nec fermentum purus. Vivamus at metus laoreet, scelerisque mauris in, venenatis turpis. Sed tempor rhoncus commodo. Nam dignissim lorem mauris, vitae maximus magna gravida sit amet. Donec non magna porta, viverra lectus sit amet, sollicitudin nisl. Vivamus maximus luctus est, laoreet aliquet leo auctor eu.

Curabitur convallis, enim nec dignissim aliquet, massa orci luctus magna, eget venenatis ex neque quis justo. Suspendisse vel lectus aliquam, fermentum lacus ut, facilisis velit. Sed auctor et elit quis sagittis. Nulla facilisi. Sed at consectetur tortor. Duis consectetur quam dolor, ac aliquet orci aliquam quis. Vivamus fringilla finibus quam, ac ornare nisl molestie nec. Nulla ut nunc tellus. Nulla id nibh felis.

Nam eu neque finibus, sodales orci euismod, consectetur lectus. Ut tristique nec turpis nec eleifend. Morbi non posuere ipsum, quis tristique nulla. Nullam vulputate elit ac mi dictum ultrices. Praesent sed odio eros. Duis luctus leo pulvinar porta scelerisque. Quisque eget leo rhoncus, blandit augue sed, pellentesque quam. Vestibulum quis nunc eu felis pulvinar dictum a sit amet risus. 



Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et congue ex, et sagittis orci. Integer mollis urna id lacus commodo porta. Aenean et nunc arcu. Sed bibendum leo eu dui mattis volutpat eget at risus. Nunc dapibus justo non finibus porttitor. Sed in aliquet quam, vel interdum elit. Fusce mi leo, blandit et sollicitudin eu, gravida quis lorem. Proin dignissim neque enim, id condimentum diam tincidunt vitae. Aliquam lorem leo, congue a turpis ac, tincidunt gravida libero. Ut et laoreet lorem, vitae porta justo. Fusce vehicula, est sed rutrum bibendum, leo arcu scelerisque orci, eget fringilla ex nisi vitae quam. Donec pharetra, lacus nec tristique finibus, erat velit molestie est, ac iaculis nisl lectus eu massa.

Vestibulum porttitor risus et nisi tempor, et tristique justo hendrerit. Morbi porttitor dui vel tempus imperdiet. Ut lorem mi, suscipit sed sem in, pellentesque vehicula odio. Donec porta mi ut lacus maximus, nec mollis quam tincidunt. Fusce at laoreet odio, a molestie turpis. Sed non est lectus. Praesent eleifend mollis mi, eu pharetra metus tempus vitae. Phasellus at sollicitudin massa. Vestibulum viverra fermentum sem, eget tempus elit fringilla quis. Nunc est diam, accumsan eget vulputate sed, ultricies non magna. Donec sodales dignissim est, et ultrices mauris euismod luctus. Nunc egestas elementum felis vel gravida. Nunc interdum, enim sit amet molestie tempus, elit tellus rutrum justo, nec aliquet urna libero sit amet est. Praesent luctus est massa, quis convallis arcu auctor a. Morbi fermentum velit vel elementum tempus. Donec eu sem nisl.

Morbi aliquam pretium elit, eget placerat leo consequat a. Praesent ut gravida neque, vel mattis ligula. Proin facilisis, turpis vitae blandit vehicula, mauris ex cursus diam, non viverra est nisi eu turpis. Mauris in maximus arcu, nec fermentum purus. Vivamus at metus laoreet, scelerisque mauris in, venenatis turpis. Sed tempor rhoncus commodo. Nam dignissim lorem mauris, vitae maximus magna gravida sit amet. Donec non magna porta, viverra lectus sit amet, sollicitudin nisl. Vivamus maximus luctus est, laoreet aliquet leo auctor eu.

Curabitur convallis, enim nec dignissim aliquet, massa orci luctus magna, eget venenatis ex neque quis justo. Suspendisse vel lectus aliquam, fermentum lacus ut, facilisis velit. Sed auctor et elit quis sagittis. Nulla facilisi. Sed at consectetur tortor. Duis consectetur quam dolor, ac aliquet orci aliquam quis. Vivamus fringilla finibus quam, ac ornare nisl molestie nec. Nulla ut nunc tellus. Nulla id nibh felis.

Nam eu neque finibus, sodales orci euismod, consectetur lectus. Ut tristique nec turpis nec eleifend. Morbi non posuere ipsum, quis tristique nulla. Nullam vulputate elit ac mi dictum ultrices. Praesent sed odio eros. Duis luctus leo pulvinar porta scelerisque. Quisque eget leo rhoncus, blandit augue sed, pellentesque quam. Vestibulum quis nunc eu felis pulvinar dictum a sit amet risus. 



Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et congue ex, et sagittis orci. Integer mollis urna id lacus commodo porta. Aenean et nunc arcu. Sed bibendum leo eu dui mattis volutpat eget at risus. Nunc dapibus justo non finibus porttitor. Sed in aliquet quam, vel interdum elit. Fusce mi leo, blandit et sollicitudin eu, gravida quis lorem. Proin dignissim neque enim, id condimentum diam tincidunt vitae. Aliquam lorem leo, congue a turpis ac, tincidunt gravida libero. Ut et laoreet lorem, vitae porta justo. Fusce vehicula, est sed rutrum bibendum, leo arcu scelerisque orci, eget fringilla ex nisi vitae quam. Donec pharetra, lacus nec tristique finibus, erat velit molestie est, ac iaculis nisl lectus eu massa.

Vestibulum porttitor risus et nisi tempor, et tristique justo hendrerit. Morbi porttitor dui vel tempus imperdiet. Ut lorem mi, suscipit sed sem in, pellentesque vehicula odio. Donec porta mi ut lacus maximus, nec mollis quam tincidunt. Fusce at laoreet odio, a molestie turpis. Sed non est lectus. Praesent eleifend mollis mi, eu pharetra metus tempus vitae. Phasellus at sollicitudin massa. Vestibulum viverra fermentum sem, eget tempus elit fringilla quis. Nunc est diam, accumsan eget vulputate sed, ultricies non magna. Donec sodales dignissim est, et ultrices mauris euismod luctus. Nunc egestas elementum felis vel gravida. Nunc interdum, enim sit amet molestie tempus, elit tellus rutrum justo, nec aliquet urna libero sit amet est. Praesent luctus est massa, quis convallis arcu auctor a. Morbi fermentum velit vel elementum tempus. Donec eu sem nisl.

Morbi aliquam pretium elit, eget placerat leo consequat a. Praesent ut gravida neque, vel mattis ligula. Proin facilisis, turpis vitae blandit vehicula, mauris ex cursus diam, non viverra est nisi eu turpis. Mauris in maximus arcu, nec fermentum purus. Vivamus at metus laoreet, scelerisque mauris in, venenatis turpis. Sed tempor rhoncus commodo. Nam dignissim lorem mauris, vitae maximus magna gravida sit amet. Donec non magna porta, viverra lectus sit amet, sollicitudin nisl. Vivamus maximus luctus est, laoreet aliquet leo auctor eu.

Curabitur convallis, enim nec dignissim aliquet, massa orci luctus magna, eget venenatis ex neque quis justo. Suspendisse vel lectus aliquam, fermentum lacus ut, facilisis velit. Sed auctor et elit quis sagittis. Nulla facilisi. Sed at consectetur tortor. Duis consectetur quam dolor, ac aliquet orci aliquam quis. Vivamus fringilla finibus quam, ac ornare nisl molestie nec. Nulla ut nunc tellus. Nulla id nibh felis.

Nam eu neque finibus, sodales orci euismod, consectetur lectus. Ut tristique nec turpis nec eleifend. Morbi non posuere ipsum, quis tristique nulla. Nullam vulputate elit ac mi dictum ultrices. Praesent sed odio eros. Duis luctus leo pulvinar porta scelerisque. Quisque eget leo rhoncus, blandit augue sed, pellentesque quam. Vestibulum quis nunc eu felis pulvinar dictum a sit amet risus. 
</div>